name: Publish Snapchain
on:
  push:
    tags:
      - 'v*'

concurrency: snapchain-publish

permissions:
  contents: read
  id-token: write # OIDC Depot

jobs:
  publish-docker-image:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Log in so we can push the image layers + tags to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_WRITE_PASSWORD }}

      - uses: depot/use-action@v1
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}


      - run: ./scripts/publish-image.sh
        shell: bash
